name: biome-lint-check

on: [ push, pull_request ]

jobs:
  biome-lint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install
    - uses: biomejs/setup-biome@v2
    - name: Run Biome
      run: biome ci .