name: xo-lint-check

on: [ push, pull_request ]

jobs:
  xo-lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: XO Lint
      run: npx xo
